# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestGui(object):
    def setupUi(self, TestGui):
        TestGui.setObjectName("TestGui")
        TestGui.resize(262, 368)
        self.pushButton_send = QtWidgets.QPushButton(TestGui)
        self.pushButton_send.setGeometry(QtCore.QRect(10, 330, 131, 24))
        self.pushButton_send.setObjectName("pushButton_send")
        self.pushButton_exit = QtWidgets.QPushButton(TestGui)
        self.pushButton_exit.setGeometry(QtCore.QRect(160, 330, 80, 24))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.lineEdit = QtWidgets.QLineEdit(TestGui)
        self.lineEdit.setGeometry(QtCore.QRect(10, 300, 151, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.frame_thermo = QtWidgets.QFrame(TestGui)
        self.frame_thermo.setGeometry(QtCore.QRect(10, 20, 221, 261))
        self.frame_thermo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_thermo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_thermo.setObjectName("frame_thermo")

        self.retranslateUi(TestGui)
        QtCore.QMetaObject.connectSlotsByName(TestGui)

    def retranslateUi(self, TestGui):
        _translate = QtCore.QCoreApplication.translate
        TestGui.setWindowTitle(_translate("TestGui", "Dialog"))
        self.pushButton_send.setText(_translate("TestGui", "Send to Thermo"))
        self.pushButton_exit.setText(_translate("TestGui", "Exit"))
